### PR TITLE
Add GitHub action to automatically test package for pull request commits

### PR DESCRIPTION
**Pull request by peterdesmet**
Makes use of default template https://github.com/r-lib/actions/tree/master/examples#standard-ci-workflow

### CODE REVIEW

**Comment by peterdesmet** [comment]
GitHub actions are now triggered successfully. 🎉 The R CMD check fail due to 2 WARNINGs (with `error_on = "warning"`):

- [ ] WARNING Undocumented arguments in documentation object 'calculate_vp' 'mistnet_elevations'
- [ ] WARNING checking package dependencies ... WARNING Requires orphaned package: 'ggmap'

There are also 2 notes (does not trigger fail):

- [ ] NOTE Maintainer: 'Adriaan M. Dokter <amd427@cornell.edu>' Version contains large components (0.5.2.9419)
- [ ] NOTE sub-directories of 1Mb or more: data (1.6Mb), doc (1.0Mb), extdata (1.7Mb)

@adokter I think it is good to keep the requirement of not having warnings. What do you think?

**Comment by peterdesmet** [comment]
Test automated actions for:

/document
/style

**Comment by damianooldoni** [comment]
It seems the pr commands are not triggered as it should be. First thing coming up in my mind is that the actions settings in the repo are not set up correctly. I have no sufficient rights to go to this page, but using the same html syntax of on another repo, please go to https://github.com/adokter/bioRad/settings/actions and check sections _Actions permissions_ (set it to "Allow all actions") and _Workflow permissions_ (set it to "Read and write permissions")

**Pull request merged**
