### PR TITLE
fix 414

### PR DESCRIPTION
**Pull request by bart1**
This fixes the issue #414 the only possible disadvantage is the behaviour is the same if there are two scans with the same elevation angle  (e.g. 1 and 1 degree) or if you try to retrieve an elevation angle exactly in between two other ones e.g. `elev=2` while elevation angles 1 and 3 exist. I to always return a list as it is probably easier to work with compared to when the type returned varies.

### CODE REVIEW

**Comment by adokter** [comment]
@bart1 what is the most common use case for `all=TRUE`?

1. To retrieve multiple scans with the same elevation (like 1 and 1)
2. or to retrieve all scans equally close (like 1 and 3 when requesting 2).

If 1. is the most common use case, I think it might be easier for the user to simply return the lowest elevation angle scan when the requested elevation is right in between two scans.

**Review by adokter — CHANGES_REQUESTED** [review]
Depending on most common use case, suggest to return the lowest elevation scan when requested elevation scan is right in between two scans. This might occur quite often, and it might be more informative for the user if the length of the list indicates how many scans there are at the same requested elevation angle

**Comment by bart1** [comment]
> @bart1 what is the most common use case for `all=TRUE`?
> 
>     1. To retrieve multiple scans with the same elevation (like 1 and 1)
> 
>     2. or to retrieve all scans equally close (like 1 and 3 when requesting 2).
> 
> 
> If 1. is the most common use case, I think it might be easier for the user to simply return the lowest elevation angle scan when the requested elevation is right in between two scans.

I'm not a 100% sure. My main problem was with case 1 as the dutch radars have 3 scans at the same elevation. I do not use if for other applications. So I'm happy to return the lowest in case of conflict and not warn in that case?

**Comment by adokter** [comment]
>  I'm happy to return the lowest in case of conflict and not warn in that case?
Ok let's do that, I'll update the PR with that change

**Review by adokter — APPROVED** [review]

**Pull request merged**
