### PR TITLE
user-defineable color scale in plot.vpts()

### PR DESCRIPTION
**Pull request by adokter**
Adds arguments to plot.vpts()
* `palette`: a user-defined colorscale
* `na_color`: the color to plot NA values (gray by default)
* `nan_color`: the color to plot NaN values (default lowest value of color scale)

Necessary step for fixing #424

### CODE REVIEW

**Comment by adokter** [comment]
@peterdesmet @CeciliaNilsson709 this one is now ready for review

**Comment by adokter** [comment]
@CeciliaNilsson709 having merged https://github.com/adokter/bioRad/pull/461, do we need additional tests/snaps for the new `palette`, `na_color` and `nan_color` arguments that are being added in this pull request to `plot.vpts()`?

**Review by peterdesmet — APPROVED** [review]
- Could indeed benefit from tests to keep the coverage at the same level.
- @adokter rather than repeating the conventions in vpts.R, why not reference the conventions in vp.R?

**Comment by adokter** [comment]
@peterdesmet @CeciliaNilsson709 I had to recreate the snaps for `plot.vpts` and `plot.vpi`, but I get failed tests for the snaps, even though `devtools:check()` completes without issues on my machine (Ubuntu 18, with latest available R version 4.1.0 (2021-05-18)). Any ideas how to fix this? It seems the continuous integration system generates snaps that are slightly different, but I don't know why (my R system is fully up-to-date).

**Comment by adokter** [comment]
merging into https://github.com/adokter/bioRad/pull/506

**Pull request closed without merging**
