### PR TITLE
Hghtfixintegrate

### PR DESCRIPTION
**Pull request by bart1**
This should allow to make ppi when the vp contains the original HGHT  column.. I added a unit test to check

### CODE REVIEW

**Comment by bart1** [comment]
@adokter & @peterdesmet it just occurs to me we could also make read_vp fix the column name. That would not solve this for vp's saved from R but does solve it for vp from h5 files

**Comment by adokter** [comment]
Hi @bart1, the next release deprecates HGHT in vp and vpts objects, see #273. I think the fix should be to change the HGHT to height in your vpts and vp files before feeding them into bioRad functions (note it's not just `integrate_to_ppi` that is affected, but many other functions as well)

**Comment by adokter** [comment]
@bart1 @peterdesmet should we maybe have a function that updates old vp, vpi and vpts objects to the latest release, to keep compatibility with objects generated with older bioRad versions?

**Comment by peterdesmet** [comment]
> @bart1 @peterdesmet should we maybe have a function that updates old vp, vpi and vpts objects to the latest release, to keep compatibility with objects generated with older bioRad versions?

I think the at least the **read** functions should be flexible enough to convert data files to the new objects. Not sure we need conversion of objects themself.

**Comment by adokter** [comment]
> I think the at least the **read** functions should be flexible enough to convert data files to the new objects.

That's how it's set up now

**Comment by bart1** [comment]
The reading is currently not working like that in the devel version I have installed, see example below. Could this relate to  this line mentioning height twice? https://github.com/adokter/bioRad/blob/6cb06db6e9a692099e76aa7ef5f2908485b7f46e/R/read_vpfiles.R#L35

``` r
require(bioRad)
#> Loading required package: bioRad
#> Welcome to bioRad version 0.4.0.9261
#> Docker daemon running, Docker functionality enabled (vol2bird version 0.5.0)
dir.create('my_data')
download_vpfiles(
  date_min = "2016-10-01",
  date_max = "2016-10-20",
  radar = c("bejab"),
  directory = "my_data",
  overwrite = TRUE
)
#> Downloading data from https://lw-enram.s3-eu-west-1.amazonaws.com
#> bejab201610.zip: successfully downloaded
f<-list.files('my_data', full.names = T, recursive = T)[1]
vp<-read_vpfiles(f)
colnames(vp$data)
#>  [1] "ff"        "dbz"       "dens"      "u"         "v"        
#>  [6] "gap"       "w"         "n_dbz"     "dd"        "n"        
#> [11] "DBZH"      "HGHT"      "n_dbz_all" "eta"       "sd_vvp"   
#> [16] "n_all"
sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 18.04.3 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] bioRad_0.4.0.9261
#> 
#> loaded via a namespace (and not attached):
#>  [1] spam_2.4-0        tidyselect_0.2.5  xfun_0.11        
#>  [4] purrr_0.3.3       lattice_0.20-38   rhdf5_2.28.1     
#>  [7] colorspace_1.4-1  vctrs_0.2.0       htmltools_0.4.0  
#> [10] yaml_2.2.0        rlang_0.4.2       pillar_1.4.2     
#> [13] foreign_0.8-72    glue_1.3.1        sp_1.3-2         
#> [16] jpeg_0.1-8.1      lifecycle_0.1.0   plyr_1.8.4       
#> [19] stringr_1.4.0     fields_10.0       dotCall64_1.0-0  
#> [22] munsell_0.5.0     gtable_0.3.0      raster_3.0-7     
#> [25] RgoogleMaps_1.4.4 codetools_0.2-16  evaluate_0.14    
#> [28] knitr_1.25        maptools_0.9-9    curl_4.3         
#> [31] highr_0.8         Rcpp_1.0.3        scales_1.1.0     
#> [34] backports_1.1.5   rjson_0.2.20      ggplot2_3.2.1    
#> [37] png_0.1-7         digest_0.6.23     stringi_1.4.3    
#> [40] dplyr_0.8.3       grid_3.6.1        rgdal_1.4-8      
#> [43] tools_3.6.1       bitops_1.0-6      magrittr_1.5     
#> [46] maps_3.3.0        lazyeval_0.2.2    tibble_2.1.3     
#> [49] crayon_1.3.4      tidyr_1.0.0       pkgconfig_2.0.3  
#> [52] zeallot_0.1.0     assertthat_0.2.1  rmarkdown_1.16   
#> [55] httr_1.4.1        Rhdf5lib_1.6.3    R6_2.4.1         
#> [58] ggmap_3.0.0       compiler_3.6.1
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by adokter** [comment]
Thanks for catching that, something went wrong with refactoring HGHT to height in that line, fixed in https://github.com/adokter/bioRad/commit/ab42b7f635a708d310eb32c2ecde8eff3d9e2bbe

**Pull request closed without merging**
