### PR TITLE
Add datetime selection for vpts

### PR DESCRIPTION
**Pull request by adokter**
Adding a function to filter vpts objects for date. In practicals it keeps coming up that selecting only parts of a vpts object is not user-friendly, so adding some functionality.

Needs to be merged before Monday July 29 (Oklahoma training school coming up)

### CODE REVIEW

**Comment by adokter** [comment]
@peterdesmet added `filter_datetime()` to make date/time selections in vpts objects, please check whether it matches your ideas of data filtering (cf. https://github.com/enram/vp-processing)

**Comment by peterdesmet** [comment]
Won’t be able to review until Tuesday, so merge away. ☺️

**Comment by adokter** [comment]
I'm renaming `filter_datetime` to `filter_vpts`. While this function currently only operates on the datetime field, it would be easy to add a `quantity` keyword, and make the function filter also on other quantities, such as height and flight direction.

**Comment by peterdesmet** [comment]
Good function name. Won't be able to review further.

**Pull request merged**
