### PR TITLE
Support Vaisala IRIS format. Calculate profiles from files with with single scans/sweeps

### PR DESCRIPTION
**Pull request by adokter**
* bioRad now supports the Vaisala IRIS (IRIS RAW) radar data format (#222, adokter/vol2bird#112)

* Vertical profiles of birds can now be generated with `calculate_vp()` from a set of files containing single scans (sweeps) (#221, adokter/vol2bird#116)

* support for using local vol2bird install in `calculate_vp()` (#218)

* new function `vol2bird_version()` to check for installed vol2bird version in Docker image.

* new function `nyquist_velocity` to calculate unambiguous velocity from pulse repetition frequency (PRF) both in a single or dual-PRF scheme.

* bioRad now checks the version of the installed vol2bird Docker image, and recommends updating it with `update_docker()` when it is obsolete. More informative warnings and error messages on available Docker functionality.

* change default maximum range from 25 to 35 km (#206)

* added deprecation message for vpts class objects generated with bioRad<0.4.0, which are structurally different (#202)

* bugfix `read_cajun()` in calculation of quantity `n_dbz` (https://github.com/adokter/bioRad/commit/5adf1cb4aabe5286bbff242621d5f728a3454ebe)

* bugfix `read_vpts`, which crashed when two or more profiles had equal datetime stamps (#205)

* various documentation corrections, including difference NA/NaN/0 (#201), erroneous range units in `calculate_vp` (#207), incorrect input argument description in read_pvolfile (#216), mixed up cross-section dependency of `rtr`,`rt` versus `mtr`, `mt` (#219).

### CODE REVIEW

**Comment by adokter** [comment]
@peterdesmet @stijnvanhoey Today I committed this PR, bumping bioRad to version 0.4.0.9223. It adds several functions and updates the documentation. Do we want to regenerate the roxygen site also for these development releases?

It seems in an ideal world you would want to keep to versions of the site, one for the official CRAN release, and one for the latest development release.

But if we have to choose for now, what is the best practice? I'm inclined to keep the site up to date with the latest release, even when its a development release.

**Comment by peterdesmet** [comment]
@adokter where in [ref page](http://adriaandokter.com/bioRad/reference/index.html) should the new function `nyquist_velocity()` be listed? Note that functions are not added automatically to that page (because we chose to define our own subsections).

**Comment by peterdesmet** [comment]
I noticed that `nyquist_velocity()` is not public, but `vol2bird_version()` is. Where should the latter be listed on the reference page?

**Comment by adokter** [comment]
Sorry it was a mistake to list `nyquist_velocity()` already. That function will be added soon in another pull request from branch [rangebias](https://github.com/adokter/bioRad/blob/rangebias/).

New functions will include
* `nyquist_velocity()`
* `project_as_corrected_ppi()`
* scan_convert.R with `scan_to_spatial()` and `scan_to_raster()`
* beam.R with `beam_range()`, `beam_distance()`, `beam_profile()`, `beam_profile_overlap()`.

Since this adds much more new functionality I will make sure to ask you to review the PR when its ready. Several of the beam_* functions are now in a single file because they closely belong together, not sure whether that merits breaking 1 function 1 file philosophy.

**Comment by peterdesmet** [comment]
Ok! 👍

**Pull request merged**
