### PR TITLE
bioRad 0.6.0

### PR DESCRIPTION
**Pull request by adokter**
New CRAN release

### CODE REVIEW

**Comment by adokter** [comment]
@peterdesmet @bart1 I'm preparing here for bioRad 0.6.0 release. Things still to be finished for this release are listed under https://github.com/adokter/bioRad/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.6.0. I've moved other open issues to milestone 0.7.0. Let me know if there is anything else highly critical that needs to be part of this release? Main priority is to get something on CRAN asap as that version is quite out-dated compared to the dev branch.

**Comment by adokter** [comment]
@peterdesmet if you or someone of your team could have a look at #507 and #508 that would be very helpful for getting this release out asap

**Comment by bart1** [comment]
Just by title #162 sounds really similar to #502 so those can likely be resolved in one go

#397 is likely resolved by my recent pull request checking details is required but I think it may be closed

#376 is likely required for a release

One other thing I noticed is that i frequently require some of the none exported `bioRad:::color_*` functions to create my own plots with the familiar color scales is it worth exporting those?

**Comment by peterdesmet** [comment]
I have a pending #474, but I probably won't be able to get to that for this release. I'll have do some conflict resolves when I pick that up, but that's fine.

I'm looking into the GitHub actions issues.

**Comment by adokter** [comment]
@bart1 could you please review these lines https://github.com/adokter/bioRad/blob/a9b5308cef4690ec83e17f2861b29c15bf857590/R/operators.R#L17-L22, they are a little hard to understand for users coming to this fresh. A few basic examples might be helpful too

**Comment by adokter** [comment]
We are almost there, still pending:
* https://github.com/adokter/bioRad/pull/506#issuecomment-1116462691 documentation fix
* Github actions issue #507

**Pull request merged**
