### PR TITLE
Fix path issue

### PR DESCRIPTION
**Pull request by adokter**
This PR should fix issue #162 

Could someone check that this works also on Windows? I've only tested Mac/linux, for which the fix is qualitatively different than on Windows.

This code snippet:
```
# load bioRad
library(bioRad)

# create directory with a space
dir.create("~/dir with space")

# locate example polar volume file:
pvolfile <- system.file("extdata", "volume.h5", package = "bioRad")

# copy to a home directory with read/write permissions:
file.copy(pvolfile, "~/dir with space/volume.h5")

# test that we can process the file
calculate_vp("~/dir with space/volume.h5")
```

Should produce this output:
```
> # load bioRad
> library(bioRad)
Welcome to bioRad version 0.3.0.9170
Docker daemon running, Docker functionality enabled.
> 
> # create directory with a space
> dir.create("~/dir with space")
> 
> # locate example polar volume file:
> pvolfile <- system.file("extdata", "volume.h5", package = "bioRad")
> 
> # copy to a home directory with read/write permissions:
> file.copy(pvolfile, "~/dir with space/volume.h5")
[1] TRUE
> 
> # test that we can process the file
> calculate_vp("~/dir with space/volume.h5")
Loaded user configuration file 'options.conf' ...
Warning: radial velocities will be dealiased...
               Vertical profile (class vp)

       radar:  seang 
      source:  WMO:02606,RAD:SE50,PLC:Angelholm,NOD:seang,ORG:82,CTY:643,CMT:Swedish radar 
nominal time:  2015-10-18 18:00:00 
generated by:  vol2bird 0.3.20 
```

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
@damianooldoni can maybe test this? 

You could use CI tooling to make test these additions automatically, an example for appveyor we use is https://github.com/inbo/wateRinfo/blob/master/appveyor.yml

**Comment by peterdesmet** [comment]
I can test this too next week. There is already a Windows machine being setup to test #139. Still, writing tests + setting up CI would be a good thing to tackle in the first half of next year.

**Comment by damianooldoni** [comment]
@stijnvanhoey : unfortunately my Windows doesn't support Docker (see https://github.com/adokter/bioRad/issues/139#issuecomment-441664460). 
I get the following error:
```r
> # test that we can process the file
> calculate_vp("~/dir with space/volume.h5")
Error in calculate_vp("~/dir with space/volume.h5") : 
Requires a running Docker daemon.
```

**Comment by stijnvanhoey** [comment]
@damianooldoni no problem, thanks for the tryout

**Comment by adokter** [comment]
> I can test this too next week. There is already a Windows machine being setup to test #139.

That would be great. I'm having a Windows machine set up at Cornell too by our IT department, but that might take some time.

**Comment by adokter** [comment]
Thanks @CeciliaNilsson709 for testing. Just chexking: to test this branch you first need to install it on your computer with `devtools::install_github("adokter/bioRad@path_issue")`, have you done so?

**Comment by adokter** [comment]
Testing on Cecilia's machine worked out :)

**Pull request merged**
