### PR TITLE
Add pkgdown website

### PR DESCRIPTION
**Pull request by peterdesmet**
As discussed, add [pkgdown website](https://github.com/hadley/pkgdown), which will live at https://adokter.github.io/bioRad.

Changes:

* Build website in `docs/` with `pkgdown::build_site()` using default settings. @adokter once you accept this PR, go to GitHub settings and render site from `master/docs`
* Add `_pkgdown.yml` to customize site later (e.g. group functions)
* Add GitHub repo, GitHub issues and pkgdown website URLs in DESCRIPTION so these appear on website
* Reorder some items in DESCRIPTION following http://r-pkgs.had.co.nz/description.html, to increase readability

Preview:

pkgdown

I think this site will really help in making an effort for the documentation 😄

### CODE REVIEW

**Comment by peterdesmet** [comment]
@stijnvanhoey when I rerun `build_site()` about 20 figures in `docs/reference` are generated again with a new name (just adding extra files to repo) e.g. `basemap-3.png` instead of `basemap-1.png`. We should either:

1. Figure out how to avoid that: maybe chunks need to be named?
2. Empty /docs for every build

**Comment by stijnvanhoey** [comment]
Naming chunks should overcome this issue, as it will define the figure naming. 

If we would make the docs creation part of the CI build process (adding a `deploy` step to travis), the emptying of the docs folder would be done *by default*. Still, having named chunks remains the good practice.

**Comment by adokter** [comment]
Thanks @stijnvanhoey, I merged this pull request into master. Also updated the settings as in this screenshot:

screen shot 2017-12-08 at 2 43 01 pm

However if I follow the link, I still get an 404 error that the page is not found. Any ideas?

**Comment by stijnvanhoey** [comment]
As there is no `index.html``in your docs folder, the website won't be rendered. I'll provide a new PR with a fix on the documentation website

**Comment by stijnvanhoey** [comment]
While updating the /docs, I've seen that you ignored `.html` files, excluding he index.html from getting commited ;-)

**Pull request merged**
