### PR TITLE
unit tests test-pvolfile.R

### PR DESCRIPTION
**Pull request by adokter**
unit tests for:
* `is.odimfile()`
* `get_odim_object_type()`
* `is.pvolfile()`

### CODE REVIEW

**Comment by adokter** [comment]
punctuation and documentation needs to be checked still.

**Comment by adokter** [comment]
Code coverage is only 61.9% because the function code includes several checks for incorrectly formatted hdf5 files (that are strictly not fully ODIM compliant, but might be encountered nonetheless). Using only example files such exceptions can't be tested.

**Comment by peterdesmet** [comment]
@adokter see my 2 commits for shorter tests + updated documentation style

**Comment by peterdesmet** [comment]
@adokter this PR fails because it tests `is.odimfile()` while that function is not in the namespace. Should it be?

**Comment by adokter** [comment]
`is.odimfile` doesn't have to be in namespace, it's functionality is covered by higher-level `is.pvolfile`. I corrected the namespace by changing to `bioRad:::is.odimfile`

**Comment by adokter** [comment]
\document

**Pull request merged**
